// @ts-nocheck
/* eslint-disable */
/* tslint:disable */
/* prettier-ignore-start */
/** @jsxRuntime classic */
/** @jsx createPlasmicElementProxy */
/** @jsxFrag React.Fragment */
// This class is auto-generated by Plasmic; please do not edit!
// Plasmic Project: fiUhXe8Zsj5ebqGZX94BP2
// Component: SO_vbTacIlpeAq
import * as React from "react";
import * as p from "@plasmicapp/react-web";
import {
  hasVariant,
  classNames,
  createPlasmicElementProxy,
  deriveRenderOpts
} from "@plasmicapp/react-web";
import "@plasmicapp/react-web/lib/plasmic.css";
import * as defaultcss from "../plasmic__default_style.module.css"; // plasmic-import: global/defaultcss
import * as projectcss from "./plasmic_play_plasmic_levels_start_here.module.css"; // plasmic-import: fiUhXe8Zsj5ebqGZX94BP2/projectcss
import * as sty from "./PlasmicCompletedDualSizeProfile.module.css"; // plasmic-import: SO_vbTacIlpeAq/css
import image115Ys3I8AdEmYCbp from "./images/image11.png"; // plasmic-import: 5ys3i8ADEmYCbp/picture

export const PlasmicCompletedDualSizeProfile__VariantProps = new Array(
  "expanded"
);

export const PlasmicCompletedDualSizeProfile__ArgProps = new Array();

function PlasmicCompletedDualSizeProfile__RenderFunc(props) {
  const { variants, args, overrides, forNode } = props;
  return (
    <p.Stack
      as={"div"}
      data-plasmic-name={"root"}
      data-plasmic-override={overrides.root}
      data-plasmic-root={true}
      data-plasmic-for-node={forNode}
      hasGap={true}
      className={classNames(defaultcss.all, projectcss.root_reset, sty.root, {
        [sty.root__expanded]: hasVariant(variants, "expanded", "expanded")
      })}
    >
      <img
        data-plasmic-name={"img"}
        data-plasmic-override={overrides.img}
        alt={""}
        className={classNames(defaultcss.img, sty.img, {
          [sty.img__expanded]: hasVariant(variants, "expanded", "expanded")
        })}
        role={"img"}
        src={image115Ys3I8AdEmYCbp}
      />

      <p.Stack
        as={"div"}
        hasGap={true}
        className={classNames(defaultcss.all, sty.box__lNfDn, {
          [sty.box__expanded__lNfDn3QikB]: hasVariant(
            variants,
            "expanded",
            "expanded"
          )
        })}
      >
        <div
          className={classNames(
            defaultcss.all,
            defaultcss.__wab_text,
            sty.box___7GlGo,
            {
              [sty.box__expanded___7GlGo3QikB]: hasVariant(
                variants,
                "expanded",
                "expanded"
              )
            }
          )}
        >
          {"Totoro"}
        </div>

        <div
          className={classNames(
            defaultcss.all,
            defaultcss.__wab_text,
            sty.box__tTkx,
            {
              [sty.box__expanded__tTkx3QikB]: hasVariant(
                variants,
                "expanded",
                "expanded"
              )
            }
          )}
        >
          {"@friendlyneighbor"}
        </div>
      </p.Stack>
    </p.Stack>
  );
}

const PlasmicDescendants = {
  root: ["root", "img"],
  img: ["img"]
};

function makeNodeComponent(nodeName) {
  const func = function (props) {
    const { variants, args, overrides } = deriveRenderOpts(props, {
      name: nodeName,
      descendantNames: [...PlasmicDescendants[nodeName]],
      internalArgPropNames: PlasmicCompletedDualSizeProfile__ArgProps,
      internalVariantPropNames: PlasmicCompletedDualSizeProfile__VariantProps
    });

    return PlasmicCompletedDualSizeProfile__RenderFunc({
      variants,
      args,
      overrides,
      forNode: nodeName
    });
  };
  if (nodeName === "root") {
    func.displayName = "PlasmicCompletedDualSizeProfile";
  } else {
    func.displayName = `PlasmicCompletedDualSizeProfile.${nodeName}`;
  }
  return func;
}

export const PlasmicCompletedDualSizeProfile = Object.assign(
  // Top-level PlasmicCompletedDualSizeProfile renders the root element
  makeNodeComponent("root"),
  {
    // Helper components rendering sub-elements
    img: makeNodeComponent("img"),
    // Metadata about props expected for PlasmicCompletedDualSizeProfile
    internalVariantProps: PlasmicCompletedDualSizeProfile__VariantProps,
    internalArgProps: PlasmicCompletedDualSizeProfile__ArgProps
  }
);

export default PlasmicCompletedDualSizeProfile;
/* prettier-ignore-end */
