// @ts-nocheck
/* eslint-disable */
/* tslint:disable */
/* prettier-ignore-start */
/** @jsxRuntime classic */
/** @jsx createPlasmicElementProxy */
/** @jsxFrag React.Fragment */
// This class is auto-generated by Plasmic; please do not edit!
// Plasmic Project: fiUhXe8Zsj5ebqGZX94BP2
// Component: cQ01uZinaMXxb6
import * as React from "react";
import {
  classNames,
  createPlasmicElementProxy,
  deriveRenderOpts
} from "@plasmicapp/react-web";
import WorkspaceLabel from "../../WorkspaceLabel"; // plasmic-import: RgzyrleX8lCaW-/component
import "@plasmicapp/react-web/lib/plasmic.css";
import * as defaultcss from "../plasmic__default_style.module.css"; // plasmic-import: global/defaultcss
import * as sty from "./PlasmicTryItHere.module.css"; // plasmic-import: cQ01uZinaMXxb6/css

export const PlasmicTryItHere__VariantProps = new Array();

export const PlasmicTryItHere__ArgProps = new Array();

function PlasmicTryItHere__RenderFunc(props) {
  const { variants, args, overrides, forNode } = props;
  return (
    <WorkspaceLabel
      data-plasmic-name={"root"}
      data-plasmic-override={overrides.root}
      data-plasmic-root={true}
      data-plasmic-for-node={forNode}
      className={classNames("__wab_instance", sty.root)}
    >
      <div
        data-plasmic-name={"box"}
        data-plasmic-override={overrides.box}
        className={classNames(defaultcss.all, defaultcss.__wab_text, sty.box)}
      >
        {"Try it here:"}
      </div>
    </WorkspaceLabel>
  );
}

const PlasmicDescendants = {
  root: ["root", "box"],
  box: ["box"]
};

function makeNodeComponent(nodeName) {
  const func = function (props) {
    const { variants, args, overrides } = deriveRenderOpts(props, {
      name: nodeName,
      descendantNames: [...PlasmicDescendants[nodeName]],
      internalArgPropNames: PlasmicTryItHere__ArgProps,
      internalVariantPropNames: PlasmicTryItHere__VariantProps
    });

    return PlasmicTryItHere__RenderFunc({
      variants,
      args,
      overrides,
      forNode: nodeName
    });
  };
  if (nodeName === "root") {
    func.displayName = "PlasmicTryItHere";
  } else {
    func.displayName = `PlasmicTryItHere.${nodeName}`;
  }
  return func;
}

export const PlasmicTryItHere = Object.assign(
  // Top-level PlasmicTryItHere renders the root element
  makeNodeComponent("root"),
  {
    // Helper components rendering sub-elements
    box: makeNodeComponent("box"),
    // Metadata about props expected for PlasmicTryItHere
    internalVariantProps: PlasmicTryItHere__VariantProps,
    internalArgProps: PlasmicTryItHere__ArgProps
  }
);

export default PlasmicTryItHere;
/* prettier-ignore-end */
