// @ts-nocheck
/* eslint-disable */
/* tslint:disable */
/* prettier-ignore-start */
/** @jsxRuntime classic */
/** @jsx createPlasmicElementProxy */
/** @jsxFrag React.Fragment */
// This class is auto-generated by Plasmic; please do not edit!
// Plasmic Project: fiUhXe8Zsj5ebqGZX94BP2
// Component: 9CvEZtdoLJnhYg
import * as React from "react";
import * as p from "@plasmicapp/react-web";
import {
  hasVariant,
  classNames,
  createPlasmicElementProxy,
  deriveRenderOpts
} from "@plasmicapp/react-web";
import "@plasmicapp/react-web/lib/plasmic.css";
import * as defaultcss from "../plasmic__default_style.module.css"; // plasmic-import: global/defaultcss
import * as projectcss from "./plasmic_play_plasmic_levels_start_here.module.css"; // plasmic-import: fiUhXe8Zsj5ebqGZX94BP2/projectcss
import * as sty from "./PlasmicButton7.module.css"; // plasmic-import: 9CvEZtdoLJnhYg/css

export const PlasmicButton7__VariantProps = new Array("type", "border", "size");

export const PlasmicButton7__ArgProps = new Array("children");

function PlasmicButton7__RenderFunc(props) {
  const { variants, args, overrides, forNode } = props;
  return (
    <div
      data-plasmic-name={"root"}
      data-plasmic-override={overrides.root}
      data-plasmic-root={true}
      data-plasmic-for-node={forNode}
      className={classNames(defaultcss.all, projectcss.root_reset, sty.root, {
        [sty.root__border_link]: hasVariant(variants, "border", "link"),
        [sty.root__border_rounded]: hasVariant(variants, "border", "rounded"),
        [sty.root__size_large]: hasVariant(variants, "size", "large"),
        [sty.root__size_small]: hasVariant(variants, "size", "small"),
        [sty.root__type_danger]: hasVariant(variants, "type", "danger"),
        [sty.root__type_primary]: hasVariant(variants, "type", "primary")
      })}
    >
      <p.PlasmicSlot
        defaultContents={"Click me"}
        value={args.children}
        className={classNames(sty.slotChildren, {
          [sty.slotChildren__border_link]: hasVariant(
            variants,
            "border",
            "link"
          ),

          [sty.slotChildren__border_rounded]: hasVariant(
            variants,
            "border",
            "rounded"
          ),

          [sty.slotChildren__size_large]: hasVariant(variants, "size", "large"),
          [sty.slotChildren__size_small]: hasVariant(variants, "size", "small"),
          [sty.slotChildren__type_danger]: hasVariant(
            variants,
            "type",
            "danger"
          ),

          [sty.slotChildren__type_primary]: hasVariant(
            variants,
            "type",
            "primary"
          )
        })}
      />
    </div>
  );
}

const PlasmicDescendants = {
  root: ["root"]
};

function makeNodeComponent(nodeName) {
  const func = function (props) {
    const { variants, args, overrides } = deriveRenderOpts(props, {
      name: nodeName,
      descendantNames: [...PlasmicDescendants[nodeName]],
      internalArgPropNames: PlasmicButton7__ArgProps,
      internalVariantPropNames: PlasmicButton7__VariantProps
    });

    return PlasmicButton7__RenderFunc({
      variants,
      args,
      overrides,
      forNode: nodeName
    });
  };
  if (nodeName === "root") {
    func.displayName = "PlasmicButton7";
  } else {
    func.displayName = `PlasmicButton7.${nodeName}`;
  }
  return func;
}

export const PlasmicButton7 = Object.assign(
  // Top-level PlasmicButton7 renders the root element
  makeNodeComponent("root"),
  {
    // Helper components rendering sub-elements
    // Metadata about props expected for PlasmicButton7
    internalVariantProps: PlasmicButton7__VariantProps,
    internalArgProps: PlasmicButton7__ArgProps
  }
);

export default PlasmicButton7;
/* prettier-ignore-end */
