// @ts-nocheck
/* eslint-disable */
/* tslint:disable */
/* prettier-ignore-start */
/** @jsxRuntime classic */
/** @jsx createPlasmicElementProxy */
/** @jsxFrag React.Fragment */
// This class is auto-generated by Plasmic; please do not edit!
// Plasmic Project: fiUhXe8Zsj5ebqGZX94BP2
// Component: RgzyrleX8lCaW-
import * as React from "react";
import * as p from "@plasmicapp/react-web";
import {
  classNames,
  createPlasmicElementProxy,
  deriveRenderOpts
} from "@plasmicapp/react-web";
import "@plasmicapp/react-web/lib/plasmic.css";
import * as defaultcss from "../plasmic__default_style.module.css"; // plasmic-import: global/defaultcss
import * as projectcss from "./plasmic_play_plasmic_levels_start_here.module.css"; // plasmic-import: fiUhXe8Zsj5ebqGZX94BP2/projectcss
import * as sty from "./PlasmicWorkspaceLabel.module.css"; // plasmic-import: RgzyrleX8lCaW-/css

export const PlasmicWorkspaceLabel__VariantProps = new Array();

export const PlasmicWorkspaceLabel__ArgProps = new Array("children");

function PlasmicWorkspaceLabel__RenderFunc(props) {
  const { variants, args, overrides, forNode } = props;
  return (
    <div
      data-plasmic-name={"root"}
      data-plasmic-override={overrides.root}
      data-plasmic-root={true}
      data-plasmic-for-node={forNode}
      className={classNames(defaultcss.all, projectcss.root_reset, sty.root)}
    >
      <div
        data-plasmic-name={"box"}
        data-plasmic-override={overrides.box}
        className={classNames(defaultcss.all, sty.box)}
      >
        <p.PlasmicSlot
          defaultContents={"Objective:"}
          value={args.children}
          className={classNames(sty.slotChildren)}
        />
      </div>
    </div>
  );
}

const PlasmicDescendants = {
  root: ["root", "box"],
  box: ["box"]
};

function makeNodeComponent(nodeName) {
  const func = function (props) {
    const { variants, args, overrides } = deriveRenderOpts(props, {
      name: nodeName,
      descendantNames: [...PlasmicDescendants[nodeName]],
      internalArgPropNames: PlasmicWorkspaceLabel__ArgProps,
      internalVariantPropNames: PlasmicWorkspaceLabel__VariantProps
    });

    return PlasmicWorkspaceLabel__RenderFunc({
      variants,
      args,
      overrides,
      forNode: nodeName
    });
  };
  if (nodeName === "root") {
    func.displayName = "PlasmicWorkspaceLabel";
  } else {
    func.displayName = `PlasmicWorkspaceLabel.${nodeName}`;
  }
  return func;
}

export const PlasmicWorkspaceLabel = Object.assign(
  // Top-level PlasmicWorkspaceLabel renders the root element
  makeNodeComponent("root"),
  {
    // Helper components rendering sub-elements
    box: makeNodeComponent("box"),
    // Metadata about props expected for PlasmicWorkspaceLabel
    internalVariantProps: PlasmicWorkspaceLabel__VariantProps,
    internalArgProps: PlasmicWorkspaceLabel__ArgProps
  }
);

export default PlasmicWorkspaceLabel;
/* prettier-ignore-end */
