// @ts-nocheck
/* eslint-disable */
/* tslint:disable */
/* prettier-ignore-start */
/** @jsxRuntime classic */
/** @jsx createPlasmicElementProxy */
/** @jsxFrag React.Fragment */
// This class is auto-generated by Plasmic; please do not edit!
// Plasmic Project: fiUhXe8Zsj5ebqGZX94BP2
// Component: xRwN3d8eceeAko
import * as React from "react";
import * as p from "@plasmicapp/react-web";
import {
  classNames,
  createPlasmicElementProxy,
  deriveRenderOpts
} from "@plasmicapp/react-web";
import "@plasmicapp/react-web/lib/plasmic.css";
import * as defaultcss from "../plasmic__default_style.module.css"; // plasmic-import: global/defaultcss
import * as projectcss from "./plasmic_play_plasmic_levels_start_here.module.css"; // plasmic-import: fiUhXe8Zsj5ebqGZX94BP2/projectcss
import * as sty from "./PlasmicTask2.module.css"; // plasmic-import: xRwN3d8eceeAko/css

export const PlasmicTask2__VariantProps = new Array();

export const PlasmicTask2__ArgProps = new Array();

function PlasmicTask2__RenderFunc(props) {
  const { variants, args, overrides, forNode } = props;
  return (
    <p.Stack
      as={"div"}
      data-plasmic-name={"root"}
      data-plasmic-override={overrides.root}
      data-plasmic-root={true}
      data-plasmic-for-node={forNode}
      hasGap={true}
      className={classNames(defaultcss.all, projectcss.root_reset, sty.root)}
    >
      <div className={classNames(defaultcss.all, sty.box___8BoQp)} />

      <div
        className={classNames(
          defaultcss.all,
          defaultcss.__wab_text,
          sty.box__hp9Gc
        )}
      >
        {"Request application extension"}
      </div>
    </p.Stack>
  );
}

const PlasmicDescendants = {
  root: ["root"]
};

function makeNodeComponent(nodeName) {
  const func = function (props) {
    const { variants, args, overrides } = deriveRenderOpts(props, {
      name: nodeName,
      descendantNames: [...PlasmicDescendants[nodeName]],
      internalArgPropNames: PlasmicTask2__ArgProps,
      internalVariantPropNames: PlasmicTask2__VariantProps
    });

    return PlasmicTask2__RenderFunc({
      variants,
      args,
      overrides,
      forNode: nodeName
    });
  };
  if (nodeName === "root") {
    func.displayName = "PlasmicTask2";
  } else {
    func.displayName = `PlasmicTask2.${nodeName}`;
  }
  return func;
}

export const PlasmicTask2 = Object.assign(
  // Top-level PlasmicTask2 renders the root element
  makeNodeComponent("root"),
  {
    // Helper components rendering sub-elements
    // Metadata about props expected for PlasmicTask2
    internalVariantProps: PlasmicTask2__VariantProps,
    internalArgProps: PlasmicTask2__ArgProps
  }
);

export default PlasmicTask2;
/* prettier-ignore-end */
