// @ts-nocheck
/* eslint-disable */
/* tslint:disable */
/* prettier-ignore-start */
/** @jsxRuntime classic */
/** @jsx createPlasmicElementProxy */
/** @jsxFrag React.Fragment */
// This class is auto-generated by Plasmic; please do not edit!
// Plasmic Project: fiUhXe8Zsj5ebqGZX94BP2
// Component: XyH3a2CBCzckhY
import * as React from "react";
import {
  classNames,
  createPlasmicElementProxy,
  deriveRenderOpts
} from "@plasmicapp/react-web";
import "@plasmicapp/react-web/lib/plasmic.css";
import * as defaultcss from "../plasmic__default_style.module.css"; // plasmic-import: global/defaultcss
import * as projectcss from "./plasmic_play_plasmic_levels_start_here.module.css"; // plasmic-import: fiUhXe8Zsj5ebqGZX94BP2/projectcss
import * as sty from "./PlasmicInteractionButton.module.css"; // plasmic-import: XyH3a2CBCzckhY/css

export const PlasmicInteractionButton__VariantProps = new Array();

export const PlasmicInteractionButton__ArgProps = new Array();

function PlasmicInteractionButton__RenderFunc(props) {
  const { variants, args, overrides, forNode } = props;
  return (
    <button
      data-plasmic-name={"root"}
      data-plasmic-override={overrides.root}
      data-plasmic-root={true}
      data-plasmic-for-node={forNode}
      className={classNames(
        defaultcss.button,
        defaultcss.__wab_text,
        projectcss.root_reset,
        sty.root
      )}
    >
      {"Click me"}
    </button>
  );
}

const PlasmicDescendants = {
  root: ["root"]
};

function makeNodeComponent(nodeName) {
  const func = function (props) {
    const { variants, args, overrides } = deriveRenderOpts(props, {
      name: nodeName,
      descendantNames: [...PlasmicDescendants[nodeName]],
      internalArgPropNames: PlasmicInteractionButton__ArgProps,
      internalVariantPropNames: PlasmicInteractionButton__VariantProps
    });

    return PlasmicInteractionButton__RenderFunc({
      variants,
      args,
      overrides,
      forNode: nodeName
    });
  };
  if (nodeName === "root") {
    func.displayName = "PlasmicInteractionButton";
  } else {
    func.displayName = `PlasmicInteractionButton.${nodeName}`;
  }
  return func;
}

export const PlasmicInteractionButton = Object.assign(
  // Top-level PlasmicInteractionButton renders the root element
  makeNodeComponent("root"),
  {
    // Helper components rendering sub-elements
    // Metadata about props expected for PlasmicInteractionButton
    internalVariantProps: PlasmicInteractionButton__VariantProps,
    internalArgProps: PlasmicInteractionButton__ArgProps
  }
);

export default PlasmicInteractionButton;
/* prettier-ignore-end */
