// @ts-nocheck
/* eslint-disable */
/* tslint:disable */
/* prettier-ignore-start */
/** @jsxRuntime classic */
/** @jsx createPlasmicElementProxy */
/** @jsxFrag React.Fragment */
// This class is auto-generated by Plasmic; please do not edit!
// Plasmic Project: fiUhXe8Zsj5ebqGZX94BP2
// Component: Xh2B7dNtaG28L2
import * as React from "react";
import {
  classNames,
  createPlasmicElementProxy,
  deriveRenderOpts
} from "@plasmicapp/react-web";
import "@plasmicapp/react-web/lib/plasmic.css";
import * as defaultcss from "../plasmic__default_style.module.css"; // plasmic-import: global/defaultcss
import * as projectcss from "./plasmic_play_plasmic_levels_start_here.module.css"; // plasmic-import: fiUhXe8Zsj5ebqGZX94BP2/projectcss
import * as sty from "./PlasmicCompletedInteractionButton.module.css"; // plasmic-import: Xh2B7dNtaG28L2/css

export const PlasmicCompletedInteractionButton__VariantProps = new Array();

export const PlasmicCompletedInteractionButton__ArgProps = new Array();

function PlasmicCompletedInteractionButton__RenderFunc(props) {
  const { variants, args, overrides, forNode } = props;
  return (
    <button
      data-plasmic-name={"root"}
      data-plasmic-override={overrides.root}
      data-plasmic-root={true}
      data-plasmic-for-node={forNode}
      className={classNames(
        defaultcss.button,
        defaultcss.__wab_text,
        projectcss.root_reset,
        sty.root
      )}
    >
      {"Click me"}
    </button>
  );
}

const PlasmicDescendants = {
  root: ["root"]
};

function makeNodeComponent(nodeName) {
  const func = function (props) {
    const { variants, args, overrides } = deriveRenderOpts(props, {
      name: nodeName,
      descendantNames: [...PlasmicDescendants[nodeName]],
      internalArgPropNames: PlasmicCompletedInteractionButton__ArgProps,
      internalVariantPropNames: PlasmicCompletedInteractionButton__VariantProps
    });

    return PlasmicCompletedInteractionButton__RenderFunc({
      variants,
      args,
      overrides,
      forNode: nodeName
    });
  };
  if (nodeName === "root") {
    func.displayName = "PlasmicCompletedInteractionButton";
  } else {
    func.displayName = `PlasmicCompletedInteractionButton.${nodeName}`;
  }
  return func;
}

export const PlasmicCompletedInteractionButton = Object.assign(
  // Top-level PlasmicCompletedInteractionButton renders the root element
  makeNodeComponent("root"),
  {
    // Helper components rendering sub-elements
    // Metadata about props expected for PlasmicCompletedInteractionButton
    internalVariantProps: PlasmicCompletedInteractionButton__VariantProps,
    internalArgProps: PlasmicCompletedInteractionButton__ArgProps
  }
);

export default PlasmicCompletedInteractionButton;
/* prettier-ignore-end */
