// @ts-nocheck
/* eslint-disable */
/* tslint:disable */
/* prettier-ignore-start */
/** @jsxRuntime classic */
/** @jsx createPlasmicElementProxy */
/** @jsxFrag React.Fragment */
// This class is auto-generated by Plasmic; please do not edit!
// Plasmic Project: fiUhXe8Zsj5ebqGZX94BP2
// Component: 6RHdKIDb1Qc11o
import * as React from "react";
import * as p from "@plasmicapp/react-web";
import {
  classNames,
  createPlasmicElementProxy,
  deriveRenderOpts
} from "@plasmicapp/react-web";
import "@plasmicapp/react-web/lib/plasmic.css";
import * as defaultcss from "../plasmic__default_style.module.css"; // plasmic-import: global/defaultcss
import * as projectcss from "./plasmic_play_plasmic_levels_start_here.module.css"; // plasmic-import: fiUhXe8Zsj5ebqGZX94BP2/projectcss
import * as sty from "./PlasmicCompletedTestimonial2.module.css"; // plasmic-import: 6RHdKIDb1Qc11o/css
import Icon28Icon from "./icons/PlasmicIcon__Icon28"; // plasmic-import: K81qB-C4BAsTKV/icon
import image45KRvYMq4K9Cf7Yi from "./images/image45.png"; // plasmic-import: KRvYMq4k9cf7YI/picture

export const PlasmicCompletedTestimonial2__VariantProps = new Array();

export const PlasmicCompletedTestimonial2__ArgProps = new Array(
  "children",
  "slot2",
  "slot3",
  "slot"
);

function PlasmicCompletedTestimonial2__RenderFunc(props) {
  const { variants, args, overrides, forNode } = props;
  return (
    <p.Stack
      as={"div"}
      data-plasmic-name={"root"}
      data-plasmic-override={overrides.root}
      data-plasmic-root={true}
      data-plasmic-for-node={forNode}
      hasGap={true}
      className={classNames(defaultcss.all, projectcss.root_reset, sty.root)}
    >
      <div className={classNames(defaultcss.all, sty.box__yolOd)}>
        <p.PlasmicSlot
          defaultContents={
            <img
              data-plasmic-name={"img"}
              data-plasmic-override={overrides.img}
              alt={""}
              className={classNames(defaultcss.img, sty.img)}
              role={"img"}
              src={image45KRvYMq4K9Cf7Yi}
            />
          }
          value={args.slot}
        />
      </div>

      <Icon28Icon
        data-plasmic-name={"svg"}
        data-plasmic-override={overrides.svg}
        className={classNames(defaultcss.all, sty.svg)}
        role={"img"}
      />

      <div className={classNames(defaultcss.all, sty.box__ecniy)}>
        <div className={classNames(defaultcss.all, sty.box__tyPyi)}>
          <p.PlasmicSlot
            defaultContents={"Truly revolutionary. An incredible leap forward."}
            value={args.children}
            className={classNames(sty.slotChildren)}
          />
        </div>
      </div>

      <p.Stack
        as={"div"}
        hasGap={true}
        className={classNames(defaultcss.all, sty.box__xluO)}
      >
        <div className={classNames(defaultcss.all, sty.box__z7RG)}>
          <p.PlasmicSlot
            defaultContents={"Jane Doe"}
            value={args.slot2}
            className={classNames(sty.slotSlot2)}
          />

          <p.PlasmicSlot
            defaultContents={"VP Marketing\nPied Piper"}
            value={args.slot3}
            className={classNames(sty.slotSlot3)}
          />
        </div>
      </p.Stack>
    </p.Stack>
  );
}

const PlasmicDescendants = {
  root: ["root", "img", "svg"],
  img: ["img"],
  svg: ["svg"]
};

function makeNodeComponent(nodeName) {
  const func = function (props) {
    const { variants, args, overrides } = deriveRenderOpts(props, {
      name: nodeName,
      descendantNames: [...PlasmicDescendants[nodeName]],
      internalArgPropNames: PlasmicCompletedTestimonial2__ArgProps,
      internalVariantPropNames: PlasmicCompletedTestimonial2__VariantProps
    });

    return PlasmicCompletedTestimonial2__RenderFunc({
      variants,
      args,
      overrides,
      forNode: nodeName
    });
  };
  if (nodeName === "root") {
    func.displayName = "PlasmicCompletedTestimonial2";
  } else {
    func.displayName = `PlasmicCompletedTestimonial2.${nodeName}`;
  }
  return func;
}

export const PlasmicCompletedTestimonial2 = Object.assign(
  // Top-level PlasmicCompletedTestimonial2 renders the root element
  makeNodeComponent("root"),
  {
    // Helper components rendering sub-elements
    img: makeNodeComponent("img"),
    svg: makeNodeComponent("svg"),
    // Metadata about props expected for PlasmicCompletedTestimonial2
    internalVariantProps: PlasmicCompletedTestimonial2__VariantProps,
    internalArgProps: PlasmicCompletedTestimonial2__ArgProps
  }
);

export default PlasmicCompletedTestimonial2;
/* prettier-ignore-end */
